# `wemake` style file for nitpick
# https://raw.githubusercontent.com/andreoliwa/nitpick/v0.18.0/nitpick-style.toml

[nitpick]
minimum_version = "0.22.0"

[nitpick.styles]
include = [
  "file-structure.toml",
  "isort.toml",
  "black.toml",
  "commitizen.toml",
  "flakehell.toml",
  "mypy.toml",
  "poetry.toml",
  "pre-commit-hooks.toml",
]
