
[[".pre-commit-config.yaml".repos]]
repo = "local"

[[".pre-commit-config.yaml".repos.hooks]]
id = "tox-lint"
name = "Run tox lint"
description = "Run tox lint"
entry = "tox -e lint"
language = "system"
types = [ "python" ]
stages = [ "push", "manual" ]
